apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-deployment-generator
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-deployment-generator
    app.kubernetes.io/instance: fint-deployment-generator_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-deployment-generator:latest
  url:
    hostname: deployment.fintlabs.no
    basePath: /
  ingress:
    enabled: true
    basePath: /
    middlewares:
      - fint-deployment-generator-sso
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
  restartPolicy: Always
  replicas: 1