apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-deployment-generator
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-deployment-generator
    app.kubernetes.io/instance: fint-deployment-generator_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-deployment-generator:latest
  imagePullPolicy: Always
  prometheus:
    enabled: true
    port: '8080'
    path: /actuator/prometheus
  url:
    hostname: deployment.fintlabs.no
  ingress:
    enabled: true
    middlewares:
      - deployment-generator-sso
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
